### PR TITLE
Speaker comms tests

### PR DESCRIPTION
**Pull request by lclarksl**

### CODE REVIEW

**Comment by jebbinSCL** [comment]
:shipit:

**Comment by thullSL** [comment]
Have we tested what happens when the speaker-comms server is unreachable?

**Comment by lclarksl** [comment]
No. What do we want to happen?

**Comment by thullSL** [comment]
I dunno, it's supposed to be "handled gracefully" by the front end. Maybe an empty map?

**Comment by lclarksl** [comment]
Added a story in JIRA

**Comment by thullSL** [comment]
[BRITECHSRM-111](https://int.scottlogic.co.uk/jira/browse/BRITECHSRM-111)
:shipit:

**Pull request merged**
